In [3]:
#creating array
import numpy as np
a=np.array([10,20,30,40])
b=np.array([[10,20],[30,40]])
c=np.array([[[10,20],[30,40],[50,60]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)

1
2
3


In [7]:
d=np.array([10,20,30,40],ndmin=7)
e=np.array([2,3,4,5,6,7],ndmin=8)
print(d.ndim)
print(e.ndim)

7
8


In [8]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [13]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[::2])

[1 3 5 7]


In [14]:
import numpy as np
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 1:4])


[[2 3 4]
 [7 8 9]]


In [18]:
arr = np.array([10, 15, 20, 25, 30, 35, 40])
print(arr[2:4])

[20 25]


In [20]:
rr = np.array([10, 15, 20, 25, 30, 35, 40])

print(arr[0:4])

[10 15 20 25]


In [7]:
import numpy as np
arr1= np.array([1, 2, 3, 4],dtype=bool)
arr2=print(arr1.dtype)
arr3= np.array([1, 2, 3, 4],dtype='f')
arr4=print(arr3.dtype)

bool
float32


In [8]:
a1=np.array([1.1,1.2,1.3,1.4],dtype='i')
a2=print(a1.dtype)
a3=np.array([1.1,1.2,1.3,1.4],dtype=bool)
a4=print(a3.dtype)

int32
bool


In [16]:
import numpy as np
x= np.array([1.1, 2.1, 3.1])
b = x.astype('i')
print(b)
z=b.copy()
print(z)
y=b.view()
print(y)

[1 2 3]
[1 2 3]
[1 2 3]


In [24]:
x=np.array([1,2,3,4])
b=x.astype(bool)
print(b)
c=x.astype('f')
print(c)
d=c.astype('i')
print(d)
e=c.astype(bool)
print(e)
z=e.copy()
print(z)
y=e.view()
print(y)

[ True  True  True  True]
[1. 2. 3. 4.]
[1 2 3 4]
[ True  True  True  True]
[ True  True  True  True]
[ True  True  True  True]


In [1]:
#finding std deviation
import numpy as np
x=[78,78,85,85,88,88,90,92,92,96]
print(np.std(x))

5.582114294781145


In [2]:
import numpy as np
x=[78,78,85,85,88,88,90,92,92,96]
print(np.median(x))

88.0


In [1]:
import numpy as np
x=[78,78,85,85,88,88,90,92,92,96]
print(np.var(x))

31.160000000000004


In [10]:
#print 12 to 36 within 9 steps
#find min() and max() value of the output values
#sqrt of the copied values
import numpy as np
arr=(12,13,14)
print(arr[12:36:9])

[]


In [6]:
min_value = np.min(arr)
max_value = np.max(arr)
print("Minimum value:", min_value)
print("Maximum value:", max_value)

Minimum value: 12.0
Maximum value: 36.0


In [7]:
a1=arr.copy()
print(a1)

[12. 15. 18. 21. 24. 27. 30. 33. 36.]


In [8]:
a2=np.sqrt(arr)
print(a2)

[3.46410162 3.87298335 4.24264069 4.58257569 4.89897949 5.19615242
 5.47722558 5.74456265 6.        ]


In [2]:
#shaping
import numpy as np
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [2]:
import numpy as np
arr1D=np.array([1, 2, 3, 4, 5])
for element in arr1D:
    print(element)


1
2
3
4
5


In [8]:
import numpy as np
arr_2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
for i in arr_2d:
     for j in i:
            print(j)

1
2
3
4
5
6
7
8
9


In [2]:
import numpy as np
arr_3d = np.array([[[1, 2, 3],[4, 5, 6],[7, 8, 9]],[[10, 11, 12],[13, 14, 15], [16, 17, 18]]])
for i in arr_3d:
    for j in i:
        for k in j:
            print(k)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18


In [5]:
import numpy as np
arr_3d = np.array([[[1, 2, 3],[4, 5, 6],[7, 8, 9]],[[10, 11, 12],[13, 14, 15], [16, 17, 18]]])
for i in np.nditer(arr_3d):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18


In [6]:
import numpy as np
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for x in np.nditer(arr[:, ::2]):
      print(x)

1
3
5
7


In [7]:
import numpy as np
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for abc,x in np.ndenumerate(arr):
    print(abc,x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [8]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [3]:
import numpy as np
arr1=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])
newarr=np.array_split(arr1, 4)
print(newarr)


[array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 11]), array([12, 13, 14])]


In [6]:
import numpy as np
arr1=np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
newarr=np.array_split(arr1, 3)
print(newarr)


[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [8]:
#horizontal-row split
import numpy as np
arr1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.hsplit(arr1, 3)
print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [10]:
#vertical-column split
import numpy as np
arr1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.vsplit(arr1, 3)
print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [3]:
import numpy as np
arr1=np.array([1,2,3,4,5,6,6,4,7,6])
x=np.where(arr1==4)
print(x)

(array([3, 7], dtype=int64),)


In [5]:
import numpy as np
arr1=np.array([1,2,3,4,5,6,6,4,7,6])
x=np.where(arr1%2==0)
print(x)

(array([1, 3, 5, 6, 7, 9], dtype=int64),)


In [7]:
import numpy as np
arr1=np.array([1,2,3,4,5,6,6,4,7,6])
x=np.searchsorted(arr1,6)
print(x)

5


In [9]:
import numpy as np
arr1=np.array([1,2,3,4,5,6,6,4,7,6])
x=np.where(arr1%2==1)
print(x)

(array([0, 2, 4, 8], dtype=int64),)


In [11]:
import numpy as np
arr1=np.array([1,2,3,4,5,6,6,4,7,6])
x=np.searchsorted(arr1,7,side='right')
print(x)

10


In [14]:
import numpy as np
arr1=np.array([1,2,3,4,5,6,6,4,7,6])
x=np.searchsorted(arr1,[2, 4, 6])
print(x)

[1 3 5]


In [17]:
#create a 1d numpy array containing the numbers from 1-5.
#create 2d numpy numpy array with dimensions 3*3 filled with zeros.
#arr=np.array([1,2,3,4,5,]),how would you access the third element?
#add two numpy arrays element-wise..
#find the mean and standard deviation of numpy array 
#generate arandom 1d numpy array of 10 integer btwn 1-100
import numpy as np
arr1D= np.array([1, 2, 3, 4, 5])
print(arr1D)


[1 2 3 4 5]


In [19]:
import numpy as np
arr2D= np.array([[1,0,2],[1,0,0],[2,0,9]])
print(arr2D)


[[1 0 2]
 [1 0 0]
 [2 0 9]]


In [22]:
third_element = arr1D[2]
print(third_element)


3


In [26]:
arr1 = np.array([1, 1, 3, 4, 5])
arr2 = np.array([5, 4, 3, 6,4 ])
result = arr1 + arr2
print(result)


[ 6  5  6 10  9]


In [29]:
mean_value = np.mean(arr1)
print(mean_value)
std_deviation = np.std(arr1)
print(std_deviation)


2.8
1.6


In [30]:
x=np.linspace(1,100,10,dtype='i')
print(x)

[  1  12  23  34  45  56  67  78  89 100]


In [9]:
a4=np.array([[[1,2],[2,3],[3,5]]])
print(a4.shape)
print(a4.dtype)

(1, 3, 2)
int32


In [14]:
arr=np.array([1,2,3,4,5,6,7,8])
print(arr.shape)
print(arr.reshape(2,4))
print(arr.reshape(4,2))
print(arr.reshape(8,1))
print(arr.reshape(1,8))

(8,)
[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
[[1 2 3 4 5 6 7 8]]


In [16]:
arr1=np.array([1,2,3,4,5,6],ndmin=6)
print(arr1)

[[[[[[1 2 3 4 5 6]]]]]]


In [21]:
arr=np.array([1,2,3,4,5,6,7,8])
arr5=arr.copy()
print(arr5)
arr6=arr5.view()
print(arr6)
arr5[3]=30
print(arr5)
arr6[2]=12
print(arr6)

[1 2 3 4 5 6 7 8]
[1 2 3 4 5 6 7 8]
[ 1  2  3 30  5  6  7  8]
[ 1  2 12 30  5  6  7  8]


In [27]:
#for loop- initialisation,text expression/condition, updation
arr=np.array([2,12,16,23,27,34,39,40])
for x in arr:
    print(x)
    print("data type is",x.dtype)

2
data type is int32
12
data type is int32
16
data type is int32
23
data type is int32
27
data type is int32
34
data type is int32
39
data type is int32
40
data type is int32


In [28]:
arr=np.array([2,12,16,23,27,34,39,40])
for x in np.nditer(arr):
    print(x)
    print("data type is",x.dtype)

2
data type is int32
12
data type is int32
16
data type is int32
23
data type is int32
27
data type is int32
34
data type is int32
39
data type is int32
40
data type is int32


In [29]:
arr=np.array([2,12,16,23,27,34,39,40])
for x in np.nditer(arr):
    print(x)

2
12
16
23
27
34
39
40


In [13]:
import numpy as np
arr = np.array([[1, 2],[3,4],[5,6],[7,8]])
for x in np.nditer(arr):
    if x in[4,5,6,7,8]:
          print(x)

4
5
6
7
8


In [16]:
import numpy as np
arr = np.array([[1, 2],[3,4],[5,6],[7,8]])
for x in np.nditer(arr[::-1,::-1]):
    print(x)

1
2
3
4
5
6
7
8


In [17]:
print(np.linspace(1,100,8))

[  1.          15.14285714  29.28571429  43.42857143  57.57142857
  71.71428571  85.85714286 100.        ]


In [2]:
import numpy as np
a1=np.array([(1,2,3,4),(4,5,6,8)])
print(a1)

[[1 2 3 4]
 [4 5 6 8]]


In [6]:
import time
import sys
a1=range(200)
print(sys.getsizeof(5)*len(a1))
b1= np.arange(300)
print(b1.size*b1.itemsize)

5600
1200


In [7]:
import numpy as np
import time
import sys
size=3000
r1=range(size)
r2=range(size)
a1=np.arange(size)
a2=np.arange(size)
start=time.time()
result=[(x,y) for x,y in zip(r1,r2)]
print((time.time()-start)*1000)
start=time.time()
result=a1+a2
print((time.time()-start)*1000)

3.517627716064453
0.0


In [8]:
a=np.array([1,2,3,4,5,6])
print(a.dtype)

int32


In [14]:
a=np.array([[1,2,3,4],[5,6,7,8]])
a=a.reshape(4,2)
print(a)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [15]:
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a[0:,3])

[4 8]


In [16]:
a=np.linspace(1,80,10)
print(a)

[ 1.          9.77777778 18.55555556 27.33333333 36.11111111 44.88888889
 53.66666667 62.44444444 71.22222222 80.        ]


In [17]:
a = np.array([1,2,3,4,5,6])
print(a.max())

6


In [18]:
a=np.array([(1,2,3,4),(3,4,5,6)])
print(a.sum(axis=0))

[ 4  6  8 10]


In [19]:
a=np.array([(1,2,3,4),(3,4,5,6)])
print(a.sum(axis=1))

[10 18]


In [22]:
a=np.arange(10).reshape(2,5)
print(a)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [23]:
a=np.array([(1,2,3,4),(3,4,5,6)])
print(np.sqrt(a))

[[1.         1.41421356 1.73205081 2.        ]
 [1.73205081 2.         2.23606798 2.44948974]]


In [26]:
a=np.array([[(1,2,3),(3,4,5),(6,7,8)]])
print(np.sqrt(a))

[[[1.         1.41421356 1.73205081]
  [1.73205081 2.         2.23606798]
  [2.44948974 2.64575131 2.82842712]]]


In [27]:
a=np.array([[[(1,2,3),(3,4,5),(6,7,8)]]])
print(np.sqrt(a))

[[[[1.         1.41421356 1.73205081]
   [1.73205081 2.         2.23606798]
   [2.44948974 2.64575131 2.82842712]]]]


In [28]:
a=np.array([[(1,2,3),(3,4,5),(6,7,8)]])
print(np.std(a))

2.211083193570267


In [31]:
a=np.array([(1,2,3,4),(3,4,5,6)])
b=np.array([(6,7,8,9),(3,4,5,9)])
print(a+b)

[[ 7  9 11 13]
 [ 6  8 10 15]]


In [32]:
a=np.array([(1,2,3,4),(3,4,5,6)])
b=np.array([(6,7,8,9),(3,4,5,9)])
print(np.vstack((a,b)))


[[1 2 3 4]
 [3 4 5 6]
 [6 7 8 9]
 [3 4 5 9]]


In [33]:
a=np.array([(1,2,3,4),(3,4,5,6)])
b=np.array([(6,7,8,9),(3,4,5,9)])
print(np.hstack((a,b)))

[[1 2 3 4 6 7 8 9]
 [3 4 5 6 3 4 5 9]]


In [34]:
b=np.array([(6,7,8,9),(3,4,5,9)])
print(b.ravel())

[6 7 8 9 3 4 5 9]
